# Generated by Django 5.0.4 on 2024-04-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-modify_dt',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='simple text', max_length=100, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
